# Bei den completed Interviews die manuellen Codes ergänzen (auskommentiert weil alte Lieferung ohne Erst-/Zweitkodierung)
# infas_kodierungen <- haven::read_dta(paste0(path_to_data, "/infas_7130_AuxCo Usability Test_Enddatensatz_Berufscodierung_20190716_1.dta"))
# infas_kodierungen$InfasOrigKldbNum <- as.numeric(infas_kodierungen$kldb)
# infas_kodierungen$InfasOrigKldBStr <- as_factor(infas_kodierungen$kldb, levels = "both")
# infas_kodierungen$InfasOrigIscoNum <- as.numeric(infas_kodierungen$isco)
# infas_kodierungen$InfasOrigIscoStr <- as_factor(infas_kodierungen$isco, levels = "both")
# infas_completed_interviews <- merge(infas_completed_interviews, infas_kodierungen[, c("INTNR", "InfasOrigKldbNum", "InfasOrigKldBStr", "InfasOrigIscoNum", "InfasOrigIscoStr")], by = "INTNR")
# noch einmal das selbe laden mit neuer Lieferung
infas_kodierungen <- haven::read_dta(paste0("orig-data/infas_7130_AuxCo Usability Test_Enddatensatz_Berufscodierung_20191017_2.dta"))
infas_kodierungen$InfasOrigKldbNum <- as.numeric(infas_kodierungen$kldb)
infas_kodierungen$InfasOrigKldBStr <- as_factor(infas_kodierungen$kldb, levels = "both")
infas_kodierungen$InfasOrigIscoNum <- as.numeric(infas_kodierungen$isco)
infas_kodierungen$InfasOrigIscoStr <- as_factor(infas_kodierungen$isco, levels = "both")
infas_kodierungen$INTERNR_neu <- as.numeric(infas_kodierungen$INTERNR)